# Задачи раздел 2 (модуль 2)

**Все задачи должны быть решены исключительно с использованием библиотеки NumPy**

**Задача 1.**

Выполните поэлементное умножение матриц (массивов) matrix_a и matrix_b . Создайте matrix_b с такими значениями, чтобы получить в итоге умножения такую матрицу:

[[ 10  20  30]

 [ 80 100 120]

 [210 240 270]]

In [ ]:
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_b =  # создайте матрицу

**Задача 2.**

Выведите:

-вторую строку и третий столбец приведенной матрицы;

-все элементы в четных столбцах;

-все элементы в нечетных строках;

-подматрицу, состоящую из двух последних строк и двух первых столбцов.



In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# Вторая строка:[5 6 7 8]
# Третий столбец:[3 7 11 15]

# Элементы с четными столбцами:
# [[ 2  4]
# [ 6  8]
# [10 12]
# [14 16]]

# Подматрица
# [[9 10]
#  [13 14]]

**Задача 3.**

Выберите подматрицу 2x2 в верхнем левом углу для каждой матрицы

In [ ]:
tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

In [ ]:
Необходимый вывод:

[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]

**Задача 4.**

Выберите из 2D массива matrix все строки, в которых есть хотя бы одно число больше 7.

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

**Задача 5.**

Есть массив grades из оценок студентов (от 0 до 100). Преобразуйте тип данных массива grades на float . Затем напишите код, который увеличит все оценки более 50 на 10% и выведет их.

In [ ]:
grades = np.array([75, 45, 60, 90, 30, 85, 40])

# нужный вывод:
# [82.5 45.  66.  99.  30.  93.5 40. ]

**Задача 6.**

Предположим, у вас есть набор данных о продажах товаров, представленный в виде двумерного массива sales_data_array. Каждая строка представляет собой информацию о продажах для конкретного товара, а столбцы содержат следующую информацию: номер товара, количество проданных единиц, и доход от продаж.

Вам необходимо написать функцию analyze_sales_data, принимающую массив sales_data и возвращающую 2 булевых значения в ответ на следующие вопросы:

* Есть ли хотя бы одна запись с нулевыми продажами (количество проданных единиц равно 0)?
* Все ли товары имеют положительный доход от продаж?

In [ ]:
def analyze_sales_data(sales_data):
    pass

sales_data_array = np.array([[1, 10, 100],
                             [2, 5, 50],
                             [3, 0, 0],
                             [4, 8, 80]])

print(f"Есть ли товары с нулевыми продажами: { }")  # первое булево значение согласно условию
print(f"Все ли товары имеют положительный доход: { }")  # второе булево значение согласно условию

**Задача 7.**

Дан массив data, содержащий информацию о студентах: имя, возраст, пол, курс и средний балл. Найдите имена, средние баллы и другую информацию студентов, которые старше 20 лет, женского пола и учатся на третьем курсе. Используйте булеву индексацию для создания маски, которая соответствует этому условию, и примените ее к массиву data.  



In [ ]:
data = np.array([
    ['Анна', 19, 'F', 1, 4.5],
    ['Борис', 21, 'M', 2, 3.7],
    ['Вера', 21, 'F', 3, 4.8],
    ['Глеб', 22, 'M', 4, 3.9],
    ['Дарья', 18, 'F', 1, 4.2],
    ['Егор', 23, 'M', 3, 4.1],
    ['Жанна', 21, 'F', 2, 4.6],
    ['Захар', 19, 'M', 1, 4.0]
])

# нужный вывод:
# [['Вера' '21' 'F' '3' '4.8']]

**Задача 8.**

У вас есть два массива: array1 = np.array([10, -15, 8, -20]) и array2 = np.array([3, 4, 2, 7]). Напишите программу для копирования знаков значений из второго массива в значения первого массива.

In [ ]:
array1 = np.array([10, -15, 8, -20])
array2 = np.array([-3, 4, -2, 7])

# нужный вывод:
# [-10.  15.  -8.  20.]

**Задача 9.**

Получите булев массив, который показывает, в каких местах первый массив содержит меньшие значения, чем второй.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

# нужный вывод:
# [ True False False]

**Задача 10.**

Создайте новый массив, который содержит элементы из arr1, если они больше 0, и элементы из arr2 в противном случае.

In [ ]:
arr1 = np.array([1, -2, 3, -4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# нужный вывод:
# [ 1 20  3 40  5]

**Задача 11.**

Создайте новый массив, который содержит 'positive', если элемент положителен, и 'non-positive' в противном случае.

In [ ]:
arr = np.array([1, -2, 0, 3, -4])

# нужный вывод:
['positive' 'non-positive' 'non-positive' 'positive' 'non-positive']

**Задача 12.**

Решите систему уравнений средствами NumPy:

3x + 2y - z = 10

x - y + 2z = 5

2x + 3y + z = 8

In [ ]:
Решение системы:
  x = 3.55
  y = 0.05
  z = 0.75

**Задача 13.**

Анализ продаж с обработкой пропущенных значений.

Дан массив ежедневных продаж за 30 дней, где пропуски обозначены как NaN. Нужно:

* Заменить пропуски медианным значением продаж
* Найти дни с продажами выше среднего
* Вычислить кумулятивную сумму продаж

In [ ]:
sales = np.array([120, 90, np.nan, 150, np.nan, 200, 110, 130, 140, 100])

In [ ]:
После заполнения пропусков: [120.  90. 125. 150. 125. 200. 110. 130. 140. 100.]
Дни с продажами выше среднего: [False False False  True False  True False  True  True False]
Индексы дней с продажами выше среднего: [3 5 7 8]
Кумулятивная сумма продаж: [ 120.  210.  335.  485.  610.  810.  920. 1050. 1190. 1290.]

**Задача 14.**

Есть матрица признаков (4 объекта, 3 признака). Нормализуйте данные:

* Приведите каждый признак к диапазону [0, 1]
* Реализуйте Z-score стандартизацию

In [ ]:
features = np.array([
    [10, 200, 5],
    [15, 300, 10],
    [12, 150, 3],
    [8, 400, 7]
])

In [ ]:
Нормализованные данные [0, 1]:
 [[0.28571429 0.2        0.28571429]
 [1.         0.6        1.        ]
 [0.57142857 0.         0.        ]
 [0.         1.         0.57142857]]
Стандартизированные данные (Z-score):
 [[-0.48336824 -0.65094455 -0.48336824]
 [ 1.45010473  0.39056673  1.45010473]
 [ 0.29002095 -1.1717002  -1.25675744]
 [-1.25675744  1.43207802  0.29002095]]

**Задача 15.**

В массиве данных найти выбросы с помощью межквартильного размаха (поиск выбросов методом IQR):

* Рассчитать 1-й и 3-й квартили
* Найти границы выбросов
* Вернуть массив без выбросов

In [ ]:
data = np.array([15, 12, 18, 21, 24, 45, 28, 11, 17, 120])

In [ ]:
Q1 (25-й процентиль): 15.5
Q3 (75-й процентиль): 27.0
IQR (межквартильный размах): 11.5
Нижняя граница выбросов: -1.75
Верхняя граница выбросов: 44.25
Выбросы: [ 45 120]
Данные без выбросов: [15 12 18 21 24 28 11 17]